In [1]:
import pandas as pd  
df = pd.DataFrame({  
"Name": ["Alice", "Bob"],  
"Cgpa": [9.5, 8.7]  
})

In [3]:
s = pd.Series([23, 24, 25, 26])  
print(s)  
print(type(s))  
# Indexing  
print(s[0])  
print(s[2])  
print(s.index)

0    23
1    24
2    25
3    26
dtype: int64
<class 'pandas.core.series.Series'>
23
25
RangeIndex(start=0, stop=4, step=1)

In [4]:
s2 = pd.Series([23, 24, 25, 26], index = ["Adam", "Eve", "Charlie", "Bob"]) 
print(s2["Eve"])    
# 24  
print(s2["Bob"])    
# 26  
# Vectorized Operations  
s1 = pd.Series([1, 2, 3])  
s2 = pd.Series([4, 5, 6])  
print(s1 + s2)  
# Mutable Values but immutable size  
s = pd.Series([1, 2, 3, 4, 5])  
s[0] = 100  
print(s)  
changed_s = s.drop(1)  
print(changed_s)  
print(s)

24
26
0    5
1    7
2    9
dtype: int64
0    100
1      2
2      3
3      4
4      5
dtype: int64
0    100
2      3
3      4
4      5
dtype: int64
0    100
1      2
2      3
3      4
4      5
dtype: int64

In [7]:
import numpy as np

In [8]:
info = {  
"Name" : ["Adam", "Eve", "Bob"],  
"Marks" : [78, 99, 85],  
"Grade" : ['B', 'O', 'A']  
}  
df = pd.DataFrame(info)  
print(df)  
print(type(df))  
print(df.index)   
print(df.columns)  
# row labels  
# column labels  
# Creating DataFrom using Numpy array  
np_arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  
df = pd.DataFrame(np_arr, columns=["Col1", "Col2", "Col3"])  
print(df)  
# Creating DataFrom using Lists  
l = [["Adam", 96], ["Eve", 75], ["Bob", 82], ["Charlie", 92]]  
df = pd.DataFrame(l, columns=["Name", "Marks"])  
print(df)

   Name  Marks Grade
0  Adam     78     B
1   Eve     99     O
2   Bob     85     A
<class 'pandas.core.frame.DataFrame'>
RangeIndex(start=0, stop=3, step=1)
Index(['Name', 'Marks', 'Grade'], dtype='object')
   Col1  Col2  Col3
0     1     2     3
1     4     5     6
2     7     8     9
      Name  Marks
0     Adam     96
1      Eve     75
2      Bob     82
3  Charlie     92

In [54]:
df_csv = pd.read_csv("C:/Users/annci/Desktop/Intership/HousePricePrediction.csv")  
# importing data from csv file  
df_json = pd.read_json("C:/Users/annci/Desktop/Intership/json_data.json")

In [55]:
df.to_csv("output.csv")   
# exporting to csv  
df.to_csv("output.csv", index=False)  # exporting without index 
df.to_json("output.json")

In [102]:
data = {  
'Name': ['Aarav', 'Isha', 'Rohan', 'Sneha', 'Vikram'],  
'Age': [25, 30, 35, 40, 45],  
'City': ['Delhi', 'Mumbai', 'Bangalore', 'Kolkata', 'Chennai'],
'Country': ['USA', 'Germany', 'America', 'Canada', 'Australia'],
'Salary': [50000,6000,90000,30000,700000],
'Gender':['Male', 'Female', 'Male', 'Female', 'Male'],
'income': [20000,90000,50000,60000,30000]
}  
df = pd.DataFrame(data)
df['Age_plus_10'] = df['Age'].apply(lambda x: x + 10)
print(df.head())  
print(df.tail())  
print(df.sample())  
print(df.info())  
print(df.describe())  
print(df.nunique())  
print(df.dtypes)  
print(df.shape)  
print(df.columns)

     Name  Age       City    Country  Salary  Gender  income  Age_plus_10
0   Aarav   25      Delhi        USA   50000    Male   20000           35
1    Isha   30     Mumbai    Germany    6000  Female   90000           40
2   Rohan   35  Bangalore    America   90000    Male   50000           45
3   Sneha   40    Kolkata     Canada   30000  Female   60000           50
4  Vikram   45    Chennai  Australia  700000    Male   30000           55
     Name  Age       City    Country  Salary  Gender  income  Age_plus_10
0   Aarav   25      Delhi        USA   50000    Male   20000           35
1    Isha   30     Mumbai    Germany    6000  Female   90000           40
2   Rohan   35  Bangalore    America   90000    Male   50000           45
3   Sneha   40    Kolkata     Canada   30000  Female   60000           50
4  Vikram   45    Chennai  Australia  700000    Male   30000           55
    Name  Age     City Country  Salary  Gender  income  Age_plus_10
3  Sneha   40  Kolkata  Canada   30000  Female   60000           50
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         5 non-null      object
 1   Age          5 non-null      int64
 2   City         5 non-null      object
 3   Country      5 non-null      object
 4   Salary       5 non-null      int64
 5   Gender       5 non-null      object
 6   income       5 non-null      int64
 7   Age_plus_10  5 non-null      int64
dtypes: int64(4), object(4)
memory usage: 452.0+ bytes
None
             Age         Salary        income  Age_plus_10
count   5.000000       5.000000      5.000000     5.000000
mean   35.000000  175200.000000  50000.000000    45.000000
std     7.905694  294983.389363  27386.127875     7.905694
min    25.000000    6000.000000  20000.000000    35.000000
25%    30.000000   30000.000000  30000.000000    40.000000
50%    35.000000   50000.000000  50000.000000    45.000000
75%    40.000000   90000.000000  60000.000000    50.000000
max    45.000000  700000.000000  90000.000000    55.000000
Name           5
Age            5
City           5
Country        5
Salary         5
Gender         2
income         5
Age_plus_10    5
dtype: int64
Name           object
Age             int64
City           object
Country        object
Salary          int64
Gender         object
income          int64
Age_plus_10     int64
dtype: object
(5, 8)
Index(['Name', 'Age', 'City', 'Country', 'Salary', 'Gender', 'income',
       'Age_plus_10'],
      dtype='object')

In [65]:
df["Country"]        
# returns a Series  
df[["City", "Age"]]

        City  Age
0      Delhi   25
1     Mumbai   30
2  Bangalore   35
3    Kolkata   40
4    Chennai   45

In [66]:
df.loc[0]   
df.loc[0:3]   
df.loc[0, "Country"]

'USA'

In [67]:
df.iloc[0]   
df.iloc[4:7]   
df.iloc[0, 2]

'Delhi'

In [68]:
df.at[0, "City"]  
df.iat[0, 2]

'Delhi'

In [70]:
df[df['Age'] > 30]  
df[(df['Age'] > 30) & (df['Salary'] > 50000)]

     Name  Age       City    Country  Salary
2   Rohan   35  Bangalore    America   90000
4  Vikram   45    Chennai  Australia  700000

In [71]:
df.query("Age > 30 and Salary < 70000")  
# Example 2  
my_Country = "IN"  
df.query("Country == @my_Country")

Empty DataFrame
Columns: [Name, Age, City, Country, Salary]
Index: []

In [72]:
df.isnull()   
df.isnull().sum()  
df.dropna()   
df.dropna(axis = 1)  
df.fillna(0)   
# True for null values (NaN)  
# counts missing vals per column  
# drops rows with missing values  
# drops cols with missing values 
# fills NaN with 0  
df["Age"] = df["Age"].fillna(df["Age"].mean())  
df.ffill()   
df.bfill()

     Name  Age       City    Country  Salary
0   Aarav   25      Delhi        USA   50000
1    Isha   30     Mumbai    Germany    6000
2   Rohan   35  Bangalore    America   90000
3   Sneha   40    Kolkata     Canada   30000
4  Vikram   45    Chennai  Australia  700000

In [76]:
df.duplicated()    
df.duplicated("Country")  
# True for duplicate rows  
# True for duplicate rows in particular col 
df.duplicated(["Country", "Gender"])

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [92]:
data2={
'Name': ['Aarav', 'Isha', 'Rohan', 'Sneha', 'Vikram'],  
'Age': [25, 30, 35, 40, 45],  
'City': ['Delhi', 'Mumbai', 'Bangalore', 'Kolkata', 'Chennai'],
'Country': ['USA', 'Germany', 'America', 'Canada', 'Australia'],
'Salary': [50000,6000,90000,30000,700000],
'income': [20000,90000,50000,60000,30000],
'gender': ['Male', 'Female', 'Male', 'Female', 'Male']
}
df2=pd.DataFrame(data2)
df2["income"] = df2["income"].astype(int)   
date_str = "2025-12-01"  
date = pd.to_datetime(date_str)  
print(date)  
print(type(date))

2025-12-01 00:00:00
<class 'pandas._libs.tslibs.timestamps.Timestamp'>

In [94]:
df2["gender"].str.lower()    
df2["gender"].str.upper()    
df2["gender"].str.capitalize()   
df2["gender"].str. capitalize()   
df2["Name"].str.split(" ")    
type(df2["Name"].str.split(" ")[0])  
# lower case  
# upper case  
# capitalize  
# capitalize  
# splits into lists 
df2["Country"].str.contains("US")  
df2["Country"].str.contains("india", case=False)

0    False
1    False
2    False
3    False
4    False
Name: Country, dtype: bool

In [99]:
df['Age_plus_10'] = df['Age'].apply(lambda x: x + 10)

In [100]:
df['City'] = df['City'].map({'Delhi':'DL', 'Mumbai':'MB'})

In [103]:
df.assign(new_income = df["income"] * 1.1)

,Name,Age,City,Country,Salary,Gender,income,Age_plus_10,new_income
0,Aarav,25,Delhi,USA,50000,Male,20000,35,22000.0
1,Isha,30,Mumbai,Germany,6000,Female,90000,40,99000.0
2,Rohan,35,Bangalore,America,90000,Male,50000,45,55000.0
3,Sneha,40,Kolkata,Canada,30000,Female,60000,50,66000.0
4,Vikram,45,Chennai,Australia,700000,Male,30000,55,33000.0

In [105]:
df['City'] = df['City'].replace({'Delhi':'DL', 'Mumbai':'MB'})

In [106]:
df = pd.DataFrame({  
"A": [1, 2, 3],  
"B": [4, 5, 6],  
"C": [7, 8, 9] 
})  
# Rename columns A -> X, B -> Y  
df_renamed = df.rename(columns={"A": "X", "B": "Y"})  
print(df_renamed)

   X  Y  C
0  1  4  7
1  2  5  8
2  3  6  9

In [109]:
df = pd.DataFrame({
    "A": [1, 2, 3],
    "B": [4, 5, 6],
    "C": [7, 8, 9]
})

df_reordered = df[["C", "A", "B"]]

print(df_reordered)

   C  A  B
0  7  1  4
1  8  2  5
2  9  3  6

In [110]:
df.columns = ["X", "Y", "Z"]  # reorders all at once  
# Reorder columns to C, A, B  
df_reordered = df[["C", "A", "B"]]

KeyError: "None of [Index(['C', 'A', 'B'], dtype='object')] are in the [columns]"

In [111]:
sorted_df2.reset_index()  
sorted_df2.reset_index(drop=True)

NameError: name 'sorted_df2' is not defined

In [112]:
# Sorting - values & index  
df2.sort_values("Income")    
# sort values in ascending 
df2.sort_values("Income", ascending=False) # sort values in descending 
df2.sort_values(["Age", "Income"]) # sorts age,if age same then sorts income  
sorted_df2 = df2.sort_values(["Age", "Income"])  
sorted_df2.sort_index()  
# Ranking  
df2["Ranking"] = df2["Income"].rank(ascending=False, method="dense") 
df2["Ranking"] = df2["Income"].rank(ascending=False, method="min") 
df2["Ranking"] = df2["Income"].rank(ascending=False, method="max")

KeyError: 'Income'

In [113]:
df2.groupby("country")["income"].mean()

KeyError: 'country'

In [114]:
df2.groupby("gender")["income"].mean()  # mean income for each gender  
df2.groupby("country")["gender"].count() 
 # count of gender for each country  
df2.groupby("gender")["income"].max()

KeyError: 'country'

In [115]:
# applies multiple aggregate functions  
df.groupby("country")["income"].agg(["mean", "min", "max"]) 
df.groupby("country")["income"].aggregate (["mean", "min", "max"]) # alias  
# rename aggregate  
df.groupby("country")["income"].agg(avg_salary="mean", max_salary="max")  
df.groupby("country").agg({  
"age": "mean",  
"income": "mean"  
}) # aggregate on multiple cols  
df.groupby("country").agg(  
avg_age=("age", "mean"),  
avg_salary= ("income", "mean")

_IncompleteInputError: incomplete input (1486453770.py, line 12)

In [116]:
df = pd.DataFrame({  
"country": ["USA", "USA", "India", "India"],  
"year": [2020, 2021, 2020, 2021],  
"sales": [100, 120, 90, 110],  
"profit": [20, 25, 18, 22]  
})  
melted = df.melt(  
id_vars=["country", "year"],  
value_name="value"     
)  
# columns to keep  
value_vars=["sales", "profit"],  # columns to unpivot  
var_name="metric",    
# new column name for variable  
# new column name for value (default is value)  
print(melted)

  country  year variable  value
0     USA  2020    sales    100
1     USA  2021    sales    120
2   India  2020    sales     90
3   India  2021    sales    110
4     USA  2020   profit     20
5     USA  2021   profit     25
6   India  2020   profit     18
7   India  2021   profit     22

In [117]:
original = melted.pivot(  
index=["country", "year"], # cols that become the NEW row index 
columns="metric",   
)  
# col whose unique values will be the cols 
values="value (in Lakhs)" # col whose values will fill the new df  
print(pivoted)

KeyError: "None of ['metric'] are in the columns"

In [118]:
# Merging & Joining 
df_customers = pd.DataFrame({  
"customer_id": [1, 2, 3, 4], 
"name": ["Adam", "Bob", "Charlie", "Dave"]  
})  
df_orders = pd.DataFrame({  
"order_id": [101, 102, 103, 104], 
"customer_id": [2, 1, 4, 5], 
"amount": [250, 120, 300, 180]  
}) 
pd.merge(df_customers, df_orders, on="customer_id")    
# Inner Join 
pd.merge(df_customers, df_orders, on="customer_id", how="left")   # Left Join 
pd.merge(df_customers, df_orders, on="customer_id", how="right")  # Right Join 
pd.merge(df_customers, df_orders, on="customer_id", how="outer")  # Outer Join

   customer_id     name  order_id  amount
0            1     Adam     102.0   120.0
1            2      Bob     101.0   250.0
2            3  Charlie       NaN     NaN
3            4     Dave     103.0   300.0
4            5      NaN     104.0   180.0

In [119]:
df1 = pd.DataFrame({  
"id": [1, 2, 3], 
"name": ["Adam", "Bob", "Charlie"]  
})  
df2 = pd.DataFrame({  
"id": [4, 5, 6], 
"name": ["David", "Eva", "Frank"]  
}) 
pd.concat([df1, df2])         
# Row wise concatenation 
pd.concat([df1, df2], ignore_index=True)

   id     name
0   1     Adam
1   2      Bob
2   3  Charlie
3   4    David
4   5      Eva
5   6    Frank

In [120]:
df["age"].hist() 
df.plot(kind='scatter', x='age', y='income')

KeyError: 'age'